# Generated by Django 3.0.5 on 2021-11-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('startdate', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('createdate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feestrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('validitydate', models.CharField(max_length=150)),
                ('batchselected', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('qual', models.CharField(max_length=1000)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=150)),
                ('pemail', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=150)),
                ('bithdate', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('healthinfo', models.CharField(max_length=500)),
                ('lastfeesdate', models.CharField(max_length=500)),
                ('validitydate', models.CharField(max_length=150)),
                ('feespaid', models.CharField(max_length=1000)),
                ('shift', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
